config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  get "/flights", to: "flights#index"
  get 'bookings/new'
  get 'bookings/list', to:  "bookings#list_all"
  
  resources :bookings
  resources :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
require "httparty"

class BookingsController < ApplicationController

  # Move to helper
  def dollars_to_cents(dollars)
    (100 * dollars.to_r).to_i
  end


  def list_all
    request_manager = RequestManager.new()
    @transactions = request_manager.get_request("gateways", ENV['GATEWAY_TOKEN'], "transactions.json?order=desc&state=succeeded")['transactions']
  end

  def index
    @bookings = Booking.all
  end

	def new
    @selected_flight = Flight.find(params[:flight_id])
    @booking = Booking.new()
    @booking.flight_id = @selected_flight.id
  end



  def create
    safe_params = params.require(:booking).permit(:flight_id, :amount_charged, :amount_charged, :payment_token, :email, :is_pmd, :is_save_credit_card)
    @booking = Booking.new(safe_params)

    request_manager = RequestManager.new()
    if @booking.is_pmd?
      success_message = 'Successful payment through Expedia'
      purchase_params =  {
        'delivery':{
          'payment_method_token': safe_params[:payment_token],
          'url': 'https://spreedly-echo.herokuapp.com',
          'headers': 'Content-Type: application/json',
          'body': '{ "card_number": "{{credit_card_number}}" }'
        }
      }.to_json

      response = request_manager.post_request("receivers", ENV['RECIEVER_TOKEN'], "deliver.json", purchase_params)
    else

      success_message = 'Successful payment, pack your bags'
      purchase_params ={
        'transaction':{
          'payment_method_token': safe_params[:payment_token],
          'amount': dollars_to_cents(safe_params[:amount_charged]),
          'currency_code': 'USD',
          'retain_on_success': safe_params[:is_save_credit_card]
        }
      }.to_json 

      response = request_manager.post_request("gateways", ENV['GATEWAY_TOKEN'], "purchase.json", purchase_params)
    end


    if response['transaction']['succeeded'] == true
      @booking.save
      flash['success'] = success_message
      redirect_to bookings_path
    else
      if response['transaction']['message'] != ""
          flash_message = response['transaction']['message']
        else
          flash_message = "Something went wrong, danggggg. Try again?"
        end
        flash['alert'] = flash_message
        redirect_to bookings_new_path + '?flight_id=' + safe_params[:flight_id]
     end
  end
end


class RequestManager
  include HTTParty
  base_uri 'https://core.spreedly.com/v1'

  def initialize()
  end

  private def base_options
    {
      headers: {
        'Content-Type' => 'application/json'
      },
      basic_auth: {
        username: ENV['ENV_KEY'],
        password: ENV['API_KEY']
      }
    }
  end

  def get_request(path, token, endpoint)
    final_uri = path + '/' + token + '/' + endpoint
    resp = self.class.get('/' + final_uri, base_options).parsed_response
    return resp
  end

  def post_request(path, token, endpoint, request_body)
    request_options = base_options
    request_options[:body] = request_body

    
    final_uri = path + '/' + token + '/' + endpoint
    self.class.post('/' + final_uri, request_options).parsed_response
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/index.html.erb
 <%= link_to "Book another flight?", flights_path(), :method => "get", :class => "btn-sm" %>

app/views/bookings/list_all.html.erb
<h2>List of previous bookings</h2>

<table class="table">
	<tr>
		<th>Full Name</th>
		<th>Email Address</th>
		<th>Transaction Type</th>
		<th>Date Processed</th>
	</tr>

<% @transactions.each do |transaction| %>
	<% payment_method = transaction['payment_method'] 
		if payment_method.nil? # have a nil payment method in my response somehow, ugh need to handle it here
			next
		end
	%>
	<tr>
   	<td><%= transaction["payment_method"]["full_name"] %> </td>
    <td><%= transaction['payment_method']['email'] %> </td>
    <td><%= transaction['transaction_type'] %> </td>
   	<td><%= Date.parse(transaction['payment_method']['created_at']).strftime('%d-%b-%Y' ) %></td>
	</tr>
<% end %>
</table>

app/views/bookings/new.html.erb
<script src="https://core.spreedly.com/iframe/express-2.min.js"></script>

<h2>Your Selected Flight</h1>
<dl>
  <dt>From:</dt><dd><%= @selected_flight.from_airport_code %></dd>
  <dt>To:</dt><dd><%= @selected_flight.to_airport_code %></dd>
  <dt>Cost:</dt><dd>$<%= @selected_flight.price %></dd>
  <dt>Departing:</dt><dd><%= @selected_flight.departure_date %></dd>
</dl>

<p>Look good? Enter a few details below then click book it, or 
 <%= link_to "go back", flights_path, :method => "get", :class => "link" %> and select another flight</p>


<label>Full name: </label>
<input type="text" name="full_name" id="full_name" placeholder="John Smitherson" />
<br />
<label>Email address: </label>
<input type="text" name="user_email" id="user_email" placeholder="email@example.com" />
<br />
<label for="save_credit_card">Save credit card for future use? </label>
<input type="checkbox" name="save_credit_card" id="save_credit_card" />
<br />
<label for="pmd">Don't trust us? Book through Expedia instead </label>
<input type="checkbox" name="pmd" id="pmd" />
<br /><br />

<button class="btn btn-primary btn-lg btn-block" onclick="doCheckout()">Let's book it!</button></p>

<%= form_for @booking  do |f| %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :payment_token %>
  <%= f.hidden_field :amount_charged, value: @selected_flight.price %>
  <%= f.hidden_field :flight_id, value: @selected_flight.id %>
  <%= f.hidden_field :is_save_credit_card %>
  <%= f.hidden_field :is_pmd %>
<% end %>


<script type="text/javascript">

// Get this bad boy initialised on page load
(function() {
  SpreedlyExpress.init("4DfU0ASDqMiPdLIh7Y58vhQIYQV", {
    "amount": "$<%= @selected_flight.price %>",
    "company_name": "Sean Air",
    "sidebar_top_description": "We probably won't crash",
    "sidebar_bottom_description": "Hopefully"
  });
})();


function doCheckout() {
  let fullName =  document.getElementById("full_name").value;
  let email =  document.getElementById("user_email").value;

  if (!fullName || !email) {
    alert('Full name and email address are required to book');
    return;
  }

  
  SpreedlyExpress.setDisplayOptions({
    "full_name": document.getElementById("full_name").value
  });
  SpreedlyExpress.setPaymentMethodParams({
    "email": document.getElementById("user_email").value
  });

  SpreedlyExpress.openView();

  SpreedlyExpress.onPaymentMethod(function(token, paymentMethod) {
    document.getElementById('booking_email').value = document.getElementById("user_email").value;
    document.getElementById('booking_payment_token').value = token;
    document.getElementById('booking_is_save_credit_card').value = document.getElementById("save_credit_card").checked;
    document.getElementById('booking_is_pmd').value = document.getElementById("pmd").checked;
    document.getElementById('new_booking').submit();
  });

};
</script>

app/views/flights/index.html.erb
<h1>Available flights</h1>

<ul>
<% @flights.each do |flight| %>
  <li>
    
    From <%= flight.from_airport_code %> to <%= flight.to_airport_code %> for $<%= flight.price %> <%= link_to "Book this one", bookings_new_path(:flight_id => flight.id), :method => "get", :class => "btn-sm" %>
  </li>
<% end %>
</ul>
<%= link_to "See a list of all previous bookings", bookings_list_path(), :method => "get", :class => "link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spreedly Airlines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-content">

      <div class="jumbotron">
        <h2><%= link_to "Spreedly Airlines", flights_path(), :method => "get" %></h2>
        <p>now with seatbelts for your safety</p>
      </div>

      <% 
        messages =  ''
        flash.each do |key, value|
          messages += value + '<br /><br />'
        end 
      %>
      <% if messages != '' %>
        <div class="flash-messages">    
          <div class="modal-body">
            <%= sanitize messages %>
          </div>
        </div>
      <% end %> 
      <%= yield %>
    </div>
  </body>
</html>